- name: Prepare home server
  become: yes
  hosts: home-server
  vars:
    portainer_dir: "/srv/portainer"
    dashy_dir: "/srv/dashy"
    traefik_dir: "/srv/traefik"
    domain_name: "{{ lookup('env', 'HOME_DOMAIN_ZONE') }}"
    cf_api_email: "{{ lookup('env', 'HOME_DOMAIN_CLOUDFLARE_EMAIL') }}"
    cf_api_key: "{{ lookup('env', 'HOME_DOMAIN_CLOUDFLARE_API_KEY') }}"
    network_server_ip: "{{ lookup('env', 'NETWORK_SERVER_IP') }}"
    media_server_ip: "{{ lookup('env', 'MEDIA_SERVER_IP') }}"
  roles:
    - update_upgrade
    - docker

  tasks:
    # Create a docker network
    - name: create a docker home network
      docker_network:
        name: home

    # Portainer
    - name: create portainer data folder
      file:
        path: "{{ portainer_dir }}/data"
        state: directory
        mode: 0755
        owner: "{{ ansible_user }}"

    - name: set docker-compose
      template:
        src: "../../../../docker-compose/home_server/portainer/docker-compose.yml.j2"
        dest: "{{ portainer_dir }}/docker-compose.yml"
        mode: 0600
        owner: "{{ ansible_user }}"

    - name: run dns server docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ portainer_dir }}"
        project_name: "home_server"
        state: "present"
        recreate: "always"

    # Dashy
    - name: create dashy data folder
      file:
        path: "{{ dashy_dir }}"
        state: directory
        owner: "{{ ansible_user }}"

    - name: adding acme.json file
      copy:
        content: ""
        dest: "{{ dashy_dir }}/conf.yml"
        force: false # Avoid replacing if file already exists
        mode: 0600

    - name: set docker-compose
      template:
        src: "../../../../docker-compose/home_server/dashy/docker-compose.yml.j2"
        dest: "{{ dashy_dir }}/docker-compose.yml"
        mode: 0600
        owner: "{{ ansible_user }}"

    - name: run dashy server docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ dashy_dir  }}"
        project_name: "home_server"
        state: "present"
        recreate: "always"

    # Traefik
    - name: ensures traefik dir exists
      file:
        path: "{{ traefik_dir }}"
        state: directory
        owner: "{{ ansible_user }}"

    - name: adding traefik.yml file
      template:
        src: "../../../../docker-compose/home_server/traefik/traefik.yml.j2"
        dest: "{{ traefik_dir }}/traefik.yml"
        mode: 0600

    - name: adding acme.json file
      copy:
        content: ""
        dest: "{{ traefik_dir }}/acme.json"
        force: false # Avoid replacing if file already exists
        mode: 0600

    - name: ensures traefik config dir exists
      file:
        path: "{{ traefik_dir }}/config"
        state: directory
        owner: "{{ ansible_user }}"

    - name: adding config files
      template:
        src: "{{ item }}"
        dest: "{{ traefik_dir }}/config/{{ item | basename | regex_replace('\\.j2$', '') }}"
      with_fileglob:
        - ../../../../docker-compose/home_server/traefik/config_templates/*.j2

    - name: set traefik docker-compose
      template:
        src: "../../../../docker-compose/home_server/traefik/docker-compose.yml.j2"
        dest: "{{ traefik_dir }}/docker-compose.yml"
        mode: 0600
        owner: "{{ ansible_user }}"

    - name: run traefik server docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ traefik_dir }}"
        project_name: "home_server"
        state: "present"
        recreate: "always"
